spring:
    data:
        mongodb:
            host: localhost
            database: projectdb
            port: 27017
            username: beom
            password: ""
            auto-index-creation: true
