spring:
    data:
        mongodb:
            host: localhost
            database: projectdb
            port: 27017
            username: beom
            password: ""
            auto-index-creation: true

discord:
    address: https://www.naver.com

selenium:
    chrome-driver-path: D:/programming/WebDriver/bin/chromedriver.exe
