server:
    port: 10080

spring:
    data:
        mongodb:
            host: localhost
            database: projectdb
            port: 27017
            username: beom
            password: ""
            auto-index-creation: true

discord:
    endpoint:
    channel: 일반
    keywords:
        - 토트넘
        - 맨유

spotv:
    url: https://www.youtube.com/user/spotv/videos?view=0&sort=dd&flow=grid
    find-per-loop: 60
    max-find-video: 3000
    interval: 600000

lh:
    interval: 600000

selenium:
    chrome-driver-path: D:/programming/WebDriver/bin/chromedriver.exe
